from typing import Any

class Server:
    def add_generic_rpc_handlers(self, handlers: list[Any]) -> None: ...
    def add_insecure_port(self, address: str) -> int: ...
    async def start(self) -> None: ...
    async def stop(self, grace: float | None = None) -> None: ...

def server(**kwargs: Any) -> Server: ...
