from typing import Any

class Redis:
    async def ping(self) -> bool: ...
    async def get(self, name: str) -> Any: ...
    async def set(self, name: str, value: Any, ex: int | None = None) -> Any: ...
    async def delete(self, *names: str) -> int: ...
    async def keys(self, pattern: str = "*") -> list[str]: ...
    async def hget(self, name: str, key: str) -> Any: ...
    async def hset(self, name: str, key: str, value: Any) -> int: ...
    async def hgetall(self, name: str) -> dict[str, Any]: ...
    async def expire(self, name: str, time: int) -> bool: ...
    async def close(self) -> None: ...
