#!/usr/bin/env bash
# Install the Obscura native-messaging host manifest into Chrome-family
# browsers on macOS and Linux.
#
# Usage:
#   ./install.sh                           # uses pinned id from ../.keys/EXTENSION_ID
#   ./install.sh <extension-id> [...]      # explicit id(s)
#
# The repo ships with a pinned public key in manifest.json, so the extension
# always loads under the same id. Passing ids explicitly is only needed if
# you're running an unkeyed fork, or if you've loaded the extension in
# multiple browsers with different keys.
#
# Environment:
#   OBSCURA_PYTHON  Python executable to launch the host with. Defaults to
#                   ${REPO_ROOT}/.venv/bin/python when it has obscura.

set -euo pipefail

HOST_NAME="com.obscura.host"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="${SCRIPT_DIR}/${HOST_NAME}.json.tmpl"
HOST_PY="${SCRIPT_DIR}/obscura_native_host.py"
PINNED_ID_FILE="${SCRIPT_DIR}/../.keys/EXTENSION_ID"

if [[ $# -lt 1 ]]; then
  if [[ -f "$PINNED_ID_FILE" ]]; then
    pinned_id="$(tr -d '[:space:]' < "$PINNED_ID_FILE")"
    if [[ -n "$pinned_id" ]]; then
      set -- "$pinned_id"
      echo "using pinned extension id: $pinned_id"
    fi
  fi
fi

if [[ $# -lt 1 ]]; then
  cat <<EOF >&2
usage: $(basename "$0") [<extension-id> ...]

No pinned id found at ${PINNED_ID_FILE}. Load the extension unpacked, copy
its id from chrome://extensions, and rerun with that id.
EOF
  exit 2
fi

chmod +x "${HOST_PY}"

# --- Resolve the launcher -------------------------------------------------
# Chrome executes the "path" field directly, so we need an executable entry
# point (not a bare .py). We write a small launcher shell script that picks
# the python interpreter at run-time.

LAUNCHER="${SCRIPT_DIR}/obscura-native-host"
PY_DEFAULT="${OBSCURA_PYTHON:-}"

# Repo root is two dirs up from packages/browser-extension/native-host.
REPO_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

# Prefer the in-repo venv python if it already has obscura installed.
# Chrome launches the native host with an arbitrary cwd, so `uv run python`
# without --directory won't find the obscura project.
if [[ -z "$PY_DEFAULT" && -x "${REPO_ROOT}/.venv/bin/python" ]]; then
  if "${REPO_ROOT}/.venv/bin/python" -c "import obscura" >/dev/null 2>&1; then
    PY_DEFAULT="${REPO_ROOT}/.venv/bin/python"
    echo "resolved python: ${PY_DEFAULT}"
  fi
fi

cat > "${LAUNCHER}" <<LAUNCHER_EOF
#!/bin/bash
# Auto-generated by install.sh — do not edit by hand.
LOG="\${HOME}/.obscura/logs/browser-extension-host.log"
mkdir -p "\$(dirname "\$LOG")"

PY="${PY_DEFAULT}"
HOST="${HOST_PY}"
REPO="${REPO_ROOT}"

# Chrome launches native hosts with a minimal environment — no shell rc,
# restricted PATH. Put Homebrew & common bins on PATH so \`gh\`, \`uv\`, etc.
# resolve when backends need them.
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:\${PATH}"

# Per-user overrides (any env vars the user wants to inject into the host —
# GH_TOKEN, OPENAI_API_KEY, ANTHROPIC_API_KEY, OBSCURA_*, etc.).
if [[ -f "\${HOME}/.obscura/browser-host.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "\${HOME}/.obscura/browser-host.env"
  set +a
fi

# Fetch a Copilot-compatible GitHub token from \`gh\` if none is set.
if [[ -z "\$GH_TOKEN" && -z "\$GITHUB_TOKEN" && -z "\$COPILOT_GITHUB_TOKEN" ]]; then
  for gh_bin in /opt/homebrew/bin/gh /usr/local/bin/gh "\$(command -v gh 2>/dev/null)"; do
    if [[ -x "\$gh_bin" ]]; then
      tok="\$("\$gh_bin" auth token 2>/dev/null || true)"
      if [[ -n "\$tok" ]]; then
        export GH_TOKEN="\$tok"
        break
      fi
    fi
  done
fi

echo "---- launcher boot \$(date) ----" >> "\$LOG"

if [[ -n "\$PY" && -x "\$PY" ]]; then
  exec "\$PY" "\$HOST"
fi
if command -v uv >/dev/null 2>&1; then
  exec uv run --quiet --directory "\$REPO" python "\$HOST"
fi
if command -v python3 >/dev/null 2>&1; then
  exec python3 "\$HOST"
fi
exec python "\$HOST"
LAUNCHER_EOF
chmod +x "${LAUNCHER}"

# Sanity-check that the launcher can actually import obscura.
if ! "${LAUNCHER}" --self-check 2>/dev/null; then
  # No self-check support yet; do a direct import probe via the resolved py.
  probe_py="${PY_DEFAULT}"
  if [[ -z "$probe_py" ]]; then
    if command -v uv >/dev/null 2>&1; then
      probe_py="uv run --quiet --directory ${REPO_ROOT} python"
    else
      probe_py="python3"
    fi
  fi
  if ! eval "$probe_py -c 'import obscura'" >/dev/null 2>&1; then
    echo "warning: the resolved python cannot import obscura." >&2
    echo "         set OBSCURA_PYTHON=/path/to/python and rerun." >&2
  fi
fi

# --- Build allowed_origins array -----------------------------------------

origins=""
for ext_id in "$@"; do
  case "$ext_id" in
    *[!a-zA-Z0-9]* )
      echo "error: extension id '$ext_id' contains invalid characters" >&2
      exit 3
      ;;
  esac
  if [[ -n "$origins" ]]; then origins+=","; fi
  origins+="\"chrome-extension://${ext_id}/\""
done
origins="[${origins}]"

# --- Render manifest ------------------------------------------------------

TMP_MANIFEST="$(mktemp -t obscura-host.XXXXXX).json"
trap 'rm -f "$TMP_MANIFEST"' EXIT

sed -e "s|__HOST_PATH__|${LAUNCHER}|g" \
    -e "s|__ALLOWED_ORIGINS__|${origins}|g" \
    "${TEMPLATE}" > "${TMP_MANIFEST}"

# --- Find target directories for each browser ----------------------------

uname_s="$(uname -s)"
targets=()

case "$uname_s" in
  Darwin)
    base="${HOME}/Library/Application Support"
    targets+=(
      "${base}/Google/Chrome/NativeMessagingHosts"
      "${base}/Google/Chrome Canary/NativeMessagingHosts"
      "${base}/Chromium/NativeMessagingHosts"
      "${base}/BraveSoftware/Brave-Browser/NativeMessagingHosts"
      "${base}/Microsoft Edge/NativeMessagingHosts"
      "${base}/Arc/User Data/NativeMessagingHosts"
      "${base}/Vivaldi/NativeMessagingHosts"
    )
    ;;
  Linux)
    targets+=(
      "${HOME}/.config/google-chrome/NativeMessagingHosts"
      "${HOME}/.config/chromium/NativeMessagingHosts"
      "${HOME}/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts"
      "${HOME}/.config/microsoft-edge/NativeMessagingHosts"
      "${HOME}/.config/vivaldi/NativeMessagingHosts"
    )
    ;;
  *)
    echo "error: unsupported OS: $uname_s" >&2
    exit 4
    ;;
esac

installed=0
for dir in "${targets[@]}"; do
  parent="$(dirname "$dir")"
  # Only install for browsers whose user-data parent actually exists.
  if [[ -d "$parent" ]]; then
    mkdir -p "$dir"
    cp "${TMP_MANIFEST}" "${dir}/${HOST_NAME}.json"
    echo "installed: ${dir}/${HOST_NAME}.json"
    installed=$((installed + 1))
  fi
done

if [[ $installed -eq 0 ]]; then
  echo "warning: no supported browser directories found" >&2
  exit 5
fi

# --- Kill any stale host processes ---------------------------------------
# Chrome keeps the native host alive across messages. Without this, the
# service worker would keep talking to the old process until Chrome decides
# to restart it.
killed=$(pkill -f "obscura_native_host\.py" 2>/dev/null && echo yes || echo no)
if [[ "$killed" == "yes" ]]; then
  echo "killed stale native host process(es)"
fi

cat <<EOF

Installed ${HOST_NAME} manifest into ${installed} browser profile(s).
  launcher : ${LAUNCHER}
  host     : ${HOST_PY}

Next: reload the Obscura card on chrome://extensions so the service worker
restarts and reconnects (the native host is already cleared). Then open
the side panel.

Logs:
  tail -f "\${OBSCURA_HOME:-\$HOME/.obscura}/logs/browser-extension-host.log"
EOF
