"""Test-friendly shim for legacy crawler tests.

This module wraps `scripts.crawlers` but routes calls through shim-level
symbols so pytest patches on `crawlers.*` take effect.
"""

from __future__ import annotations

from typing import Any

from scripts import crawlers as _c

FileEntry = _c.FileEntry
CrawlResult = _c.CrawlResult
split_mermaid_diagrams = _c.split_mermaid_diagrams
generate_index = _c.generate_index
crawl_repo = _c.crawl_repo
urllib = _c.urllib
subprocess = _c.subprocess

# Expose overridable call targets (tests patch these on the shim module)
render_svg_with_mmdc = _c.render_svg_with_mmdc
render_svg_with_kroki = _c.render_svg_with_kroki


def render_single_diagram(mermaid: str) -> str | None:
    """Use shim-patchable renderers for tests; falls through to real ones."""
    svg = render_svg_with_mmdc(mermaid)
    if svg is not None:
        return svg
    try:
        return render_svg_with_kroki(mermaid)
    except Exception:
        return None


def build_stub_markdown(entry: FileEntry, raw_mermaid: str) -> str:
    diagrams = split_mermaid_diagrams(raw_mermaid)

    if not diagrams:
        return (
            f"# Diagram: {entry.repo_relative}\n\n"
            "> Auto-generated by Obscura crawlers\n\n"
            "> No valid Mermaid diagrams were generated for this file.\n"
        )

    parts: list[str] = [
        f"# Diagram: {entry.repo_relative}\n",
        "",
        "> Auto-generated by Obscura crawlers",
        "",
    ]

    for i, diagram in enumerate(diagrams, 1):
        label = "Mermaid" if len(diagrams) == 1 else f"Diagram {i}"
        parts.append(f"## {label}")
        parts.append("")
        parts.append("```mermaid")
        parts.append(diagram.strip())
        parts.append("```")

        # Use shim-local render_single_diagram so pytest patches take effect
        svg = globals()["render_single_diagram"](diagram)
        if svg:
            parts.append(svg)
        else:
            parts.append("> SVG rendering failed")
        parts.append("")

    return "\n".join(parts).strip() + "\n"


# keep names for backward compatibility; implementations above suffice


__all__ = [
    "render_single_diagram",
    "render_svg_with_mmdc",
    "render_svg_with_kroki",
    "build_stub_markdown",
    "split_mermaid_diagrams",
    "generate_index",
    "crawl_repo",
    "FileEntry",
    "CrawlResult",
]
