"""
sdk.auth.zitadel -- Zitadel Management API client.

Provides helpers to bootstrap a Zitadel project with the roles, service
users, and API applications needed by the Obscura platform.
"""

from __future__ import annotations

import logging
from typing import Any

import httpx

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_ROLES = [
    "admin",
    "agent:copilot",
    "agent:claude",
    "agent:read",
    "sync:write",
    "sessions:manage",
]

_MGMT_BASE = "/management/v1"


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------


class ZitadelClient:
    """Thin wrapper around the Zitadel Management REST API.

    All calls use a personal access token (PAT) issued to a machine
    user that has the ``ORG_OWNER`` role, or the initial admin token
    generated by ``--init-projections-step`` / ``--masterkey``.
    """

    def __init__(self, base_url: str, token: str) -> None:
        self._base_url = base_url.rstrip("/")
        self._token = token
        self._client = httpx.AsyncClient(
            base_url=self._base_url,
            headers={
                "Authorization": f"Bearer {self._token}",
                "Content-Type": "application/json",
            },
            timeout=30,
        )

    # Read-only accessors (used in tests/observability)
    @property
    def base_url(self) -> str:
        return self._base_url

    @property
    def token(self) -> str:
        return self._token

    @property
    def client(self) -> httpx.AsyncClient:
        return self._client

    # Testing hook: replace underlying client with a stub
    def set_client_for_testing(self, client: httpx.AsyncClient) -> None:
        self._client = client

    async def close(self) -> None:
        await self._client.aclose()

    async def __aenter__(self) -> ZitadelClient:
        return self

    async def __aexit__(self, *exc: Any) -> None:
        await self.close()

    # -- helpers ----------------------------------------------------------

    async def _post(
        self, path: str, body: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        resp = await self._client.post(f"{_MGMT_BASE}{path}", json=body or {})
        resp.raise_for_status()
        return resp.json()

    async def _get(self, path: str) -> dict[str, Any]:
        resp = await self._client.get(f"{_MGMT_BASE}{path}")
        resp.raise_for_status()
        return resp.json()

    async def _put(
        self, path: str, body: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        resp = await self._client.put(f"{_MGMT_BASE}{path}", json=body or {})
        resp.raise_for_status()
        return resp.json()

    async def _delete(self, path: str) -> dict[str, Any]:
        resp = await self._client.delete(f"{_MGMT_BASE}{path}")
        resp.raise_for_status()
        return resp.json()

    # Public test/observability wrappers around HTTP helpers
    async def post_mgmt(
        self, path: str, body: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._post(path, body)

    async def get_mgmt(self, path: str) -> dict[str, Any]:
        return await self._get(path)

    async def put_mgmt(
        self, path: str, body: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        return await self._put(path, body)

    async def delete_mgmt(self, path: str) -> dict[str, Any]:
        return await self._delete(path)

    # -- projects ---------------------------------------------------------

    async def create_project(self, name: str) -> str:
        """Create a Zitadel project and return its ID."""
        data = await self._post("/projects", {"name": name})
        project_id = data.get("id", "")
        logger.info("Created project %r -> %s", name, project_id)
        return project_id

    async def list_projects(self) -> list[dict[str, Any]]:
        """List all projects in the organisation."""
        data = await self._post("/projects/_search", {"query": {}})
        return data.get("result", [])

    async def find_project_by_name(self, name: str) -> str | None:
        """Return the project ID if a project with *name* exists, else None."""
        projects = await self.list_projects()
        for p in projects:
            if p.get("name") == name:
                return p.get("id")
        return None

    # -- roles ------------------------------------------------------------

    async def add_project_role(
        self, project_id: str, role_key: str, display_name: str = ""
    ) -> None:
        """Add a role to a project."""
        await self._post(
            f"/projects/{project_id}/roles",
            {
                "roleKey": role_key,
                "displayName": display_name or role_key,
            },
        )
        logger.info("Added role %r to project %s", role_key, project_id)

    async def bulk_add_roles(self, project_id: str, roles: list[str]) -> None:
        """Add multiple roles in sequence (Zitadel has no bulk role API)."""
        for role in roles:
            try:
                await self.add_project_role(project_id, role)
            except httpx.HTTPStatusError as exc:
                if exc.response.status_code == 409:
                    logger.debug("Role %r already exists, skipping", role)
                else:
                    raise

    # -- API applications -------------------------------------------------

    async def create_api_app(self, project_id: str, name: str) -> dict[str, Any]:
        """Create an API application and return its client ID + client secret."""
        data = await self._post(
            f"/projects/{project_id}/apps/api",
            {
                "name": name,
                "authMethodType": "API_AUTH_METHOD_TYPE_BASIC",
            },
        )
        logger.info("Created API app %r (client_id=%s)", name, data.get("clientId"))
        return data

    # -- machine users (service accounts) ---------------------------------

    async def create_machine_user(
        self,
        user_name: str,
        name: str,
        description: str = "",
    ) -> str:
        """Create a machine (service) user and return its user ID."""
        # Zitadel v2 uses /v2/users/machine
        resp = await self._client.post(
            "/v2/users/machine",
            json={
                "userName": user_name,
                "name": name,
                "description": description or f"Obscura service user: {user_name}",
            },
        )
        resp.raise_for_status()
        data = resp.json()
        user_id = data.get("userId", "")
        logger.info("Created machine user %r -> %s", user_name, user_id)
        return user_id

    async def create_machine_key(self, user_id: str) -> dict[str, Any]:
        """Generate a JSON machine key for the service user."""
        resp = await self._client.post(
            f"{_MGMT_BASE}/users/{user_id}/keys",
            json={"type": "KEY_TYPE_JSON"},
        )
        resp.raise_for_status()
        data = resp.json()
        logger.info(
            "Created machine key for user %s (key id=%s)", user_id, data.get("keyId")
        )
        return data

    async def grant_project_roles(
        self,
        project_id: str,
        user_id: str,
        roles: list[str],
    ) -> None:
        """Grant project roles to a user."""
        await self._post(
            f"/projects/{project_id}/members",
            {"userId": user_id, "roles": roles},
        )
        logger.info(
            "Granted roles %s to user %s on project %s", roles, user_id, project_id
        )

    async def add_user_grant(
        self,
        project_id: str,
        user_id: str,
        role_keys: list[str],
    ) -> str:
        """Create a user grant (role assignment) and return its ID."""
        data = await self._post(
            f"/users/{user_id}/grants",
            {"projectId": project_id, "roleKeys": role_keys},
        )
        grant_id = data.get("userGrantId", "")
        logger.info("Created user grant %s for user %s", grant_id, user_id)
        return grant_id

    # -- personal access tokens -------------------------------------------

    async def create_pat(self, user_id: str) -> str:
        """Create a personal access token for the given user. Returns the token string."""
        resp = await self._client.post(
            f"{_MGMT_BASE}/users/{user_id}/pats",
            json={},
        )
        resp.raise_for_status()
        data = resp.json()
        return data.get("token", "")

    # -- OIDC info --------------------------------------------------------

    async def get_oidc_config(self) -> dict[str, Any]:
        """Fetch the OIDC well-known configuration."""
        resp = await self._client.get("/.well-known/openid-configuration")
        resp.raise_for_status()
        return resp.json()


# ---------------------------------------------------------------------------
# Bootstrap helper
# ---------------------------------------------------------------------------


async def bootstrap(
    base_url: str,
    admin_token: str,
    project_name: str = "Obscura",
    roles: list[str] | None = None,
    service_user_name: str = "obscura-admin",
) -> dict[str, Any]:
    """One-shot bootstrap: create project, roles, and admin service user.

    Returns a dict with ``project_id``, ``user_id``, ``machine_key``,
    ``jwks_uri``, and ``audience``.
    """
    roles = roles or DEFAULT_ROLES

    async with ZitadelClient(base_url, admin_token) as z:
        # 1. Find or create project
        project_id = await z.find_project_by_name(project_name)
        if project_id:
            logger.info("Project %r already exists (%s)", project_name, project_id)
        else:
            project_id = await z.create_project(project_name)

        # 2. Create roles
        await z.bulk_add_roles(project_id, roles)

        # 3. Create admin service user
        try:
            user_id = await z.create_machine_user(
                user_name=service_user_name,
                name="Obscura Admin Service Account",
            )
        except httpx.HTTPStatusError as exc:
            if exc.response.status_code == 409:
                logger.info("Service user %r already exists", service_user_name)
                user_id = ""
            else:
                raise

        machine_key: dict[str, Any] = {}
        if user_id:
            # Grant admin role
            await z.add_user_grant(project_id, user_id, ["admin"])
            # Generate key
            machine_key = await z.create_machine_key(user_id)

        # 4. Get OIDC metadata
        oidc = await z.get_oidc_config()

        return {
            "project_id": project_id,
            "user_id": user_id,
            "machine_key": machine_key,
            "jwks_uri": oidc.get("jwks_uri", f"{base_url}/.well-known/jwks.json"),
            "audience": project_id,
            "issuer": oidc.get("issuer", base_url),
        }
